-- Member 1 Work

CREATE TABLE LABEL(
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  TITLE VARCHAR,
  COLOR VARCHAR
);

CREATE TABLE BOOKS(
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  PUBLISHER VARCHAR,
  COVER_STATE VARCHAR,
  PUBLISH_DATE DATE,
  ARCHIVED BOOLEAN,
);
